# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('latitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Longitud')),
                ('estate_geo', models.CharField(blank=True, default='I', max_length=1, null=True, verbose_name='estado geografico')),
            ],
        ),
    ]
