# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20191202_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'managed': True, 'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
    ]
