# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-02 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20191202_1629'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
